#! /bin/bash

input=$1
if [ -z $1 ]; then
	input="develop"
fi

cd backend
if [ $input = "--prod" ]; then
	node dboptions/create-proddata.js
else
	node dboptions/create-fakedata.js
fi
cd ..

forego start
