'use strict';

module.exports = {
  AccessToken: [],
  ACL: [],
  Role: [],
  RoleMapping: [],
  usuario: [],
  moneda: [],
  'asesoria_personal': [],
  'disputa': [],
  instruccion: [],
  pago: [],
  'comentario_asesoria': [],
  'answer_asesoria': [],
  mercado: [],
  mercado: [],
  titulo: [],
  contenidoMoneda: [],
  messageRoom: [],
  userMessage: [],
  noticia: [],
  'comentario_noticia': [],
  'answer_noticia': [],
  notification: [],
  followUser: [],
  followUser: [],
  signal: [],
  punto: [],
  position: [],
  Suscripcion: [],
  'comentario_senal': [],
  'answer-senal': [],
  transaccion: [],
  solicitud: [],
};

